feat: Adapt from passmenu instead

diff --git a/jpassmenu b/jpassmenu
--- a/jpassmenu
+++ b/jpassmenu
@@ -1,89 +1,30 @@
-#!/bin/sh
+#!/usr/bin/env bash
+# Adapted from: https://git.zx2c4.com/password-store/plain/contrib/dmenu/passmenu
 
-menuprog='rofi -dmenu'
-action='clip'
+shopt -s nullglob globstar
 
-command_is_available() {
-	if command -v "$1" >/dev/null; then
-		return 0
-	else
-		echo "[ERROR] Couldn't find '$1'"
-		return 1
-	fi
-}
-
-help_msg="Jalil's passmenu script
-
-Usage: $0 [OPTIONS]
-
-OPTIONS:
-    -c, --clip         Copy password to clipboard [this is the default action]
-    -s, --show         Print the password to stdout
-    -q, --qrcode       Print the password as a QR code using qrencode
-    -m, --menu <PROG>  The dmenu compatible command to use [default: $menuprog]
-    -h, --help         Display this help message and exit
-"
-
-while [ "$#" -gt 0 ]; do
-	case "$1" in
-		-c|--clip)
-			action='clip'
-			shift
-			;;
-		-s|--show)
-			action='show'
-			shift
-			;;
-		-q|--qrcode)
-			action='qrcode'
-			shift
-			;;
-		-m|--menu)
-			menuprog="$2"
-			shift
-			shift
-			;;
-		-h|--help)
-			echo "$help_msg"
-			exit 0
-			;;
-		-*|--*)
-			echo "[ERROR] Unknown option '$1'"
-			echo "$help_msg"
-			exit 1
-			;;
-		*)
-			echo "[ERROR] Unexpected positional argument '$1'"
-			echo "$help_msg"
-			exit 1
-			;;
-	esac
-done
-
-command_is_available pass || exit 1
-command_is_available find || exit 1
-command_is_available $menuprog || exit 1
-
-PASSWORD_STORE_DIR="${PASSWORD_STORE_DIR-$HOME/.password-store}"
-entry="$(find "$PASSWORD_STORE_DIR" -path '*.gpg' | sed "s:$PASSWORD_STORE_DIR/\(.\+\)\.gpg:\1:" | $menuprog)"
-
-if [ -z "$entry" ]; then
-	# Did not select a password, exit immediately
-	exit 0
+typeit=0
+if [[ $1 == "--type" ]]; then
+	typeit=1
+	shift
 fi
 
-case "$action" in
-	show)
-		pass show "$entry"
-		;;
-	clip)
-		pass show --clip "$entry"
-		;;
-	qrcode)
-		pass show --qrcode "$entry"
-		;;
-	*)
-		echo "[PROGRAM ERROR] invalid action"
-		exit 1
-		;;
-esac
+if [[ -z $WAYLAND_DISPLAY ]]; then
+	echo "Error: No Wayland display detected" >&2
+	exit 1
+fi
+
+prefix=${PASSWORD_STORE_DIR-~/.password-store}
+password_files=( "$prefix"/**/*.gpg )
+password_files=( "${password_files[@]#"$prefix"/}" )
+password_files=( "${password_files[@]%.gpg}" )
+
+password=$(printf '%s\n' "${password_files[@]}" | fuzzel --dmenu "$@")
+
+[[ -n $password ]] || exit
+
+if [[ $typeit -eq 0 ]]; then
+	pass show -c "$password" 2>/dev/null
+else
+	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | ydotool type --file -
+fi
